# Generated by Django 3.2.5 on 2021-07-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='destination_1',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='destination_1_nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='destination_2',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='destination_2_nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='individualpackage',
            name='starts_from',
            field=models.IntegerField(default=0),
        ),
    ]
