# Generated by Django 3.2.5 on 2021-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210721_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpackage',
            name='destination_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualpackage',
            name='destination_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
