# Generated by Django 3.2.5 on 2021-07-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210721_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
