# Generated by Django 3.2.5 on 2021-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_packagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpackage',
            name='destination_3',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='destination_3_nights',
            field=models.IntegerField(default=False),
        ),
    ]
