# Generated by Django 3.2.5 on 2021-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210723_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpackage',
            name='destination_2',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
