# Generated by Django 3.2.5 on 2021-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_individualpackage_destination_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpackage',
            name='destination_2_nights',
            field=models.IntegerField(default=0),
        ),
    ]
