# Generated by Django 3.2.5 on 2021-08-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_bannerimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerImages',
            new_name='BannerImage',
        ),
    ]
