# Generated by Django 3.2.5 on 2021-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_rename_bannerimages_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpackage',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
