# Generated by Django 3.2.5 on 2021-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_individualpackage_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description',
            field=models.CharField(default=False, max_length=1024),
        ),
    ]
