# Generated by Django 3.2.5 on 2021-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20210806_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualpackage',
            old_name='itinerary_date',
            new_name='itinerary_date_1',
        ),
        migrations.RenameField(
            model_name='individualpackage',
            old_name='itinerary_description',
            new_name='itinerary_description_1',
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date_2',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date_3',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date_4',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date_5',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_date_6',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description_2',
            field=models.CharField(default=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description_3',
            field=models.CharField(default=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description_4',
            field=models.CharField(default=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description_5',
            field=models.CharField(default=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='itinerary_description_6',
            field=models.CharField(default=False, max_length=1024),
        ),
    ]
