# Generated by Django 3.2.5 on 2021-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20210806_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('places_of_visit', models.CharField(max_length=255)),
                ('out_of_state', models.BooleanField(default=False)),
                ('lux_bus_non_ac', models.IntegerField(default=0)),
                ('lux_bus_ac', models.IntegerField(default=0)),
            ],
        ),
    ]
