# Generated by Django 3.2.5 on 2021-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_educationaltour'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaltour',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
