# Generated by Django 3.2.5 on 2021-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_educationaltour_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaltour',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaltour',
            name='nights',
            field=models.IntegerField(default=0),
        ),
    ]
