# Generated by Django 3.2.5 on 2021-08-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_groupsubpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpackage',
            name='group_packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.groupsubpackage'),
        ),
    ]
