# Generated by Django 3.2.5 on 2021-08-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_leftimages_rightimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_package', models.CharField(default=False, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='LeftImages',
            new_name='LeftImage',
        ),
        migrations.RenameModel(
            old_name='RightImages',
            new_name='RightImage',
        ),
        migrations.AddField(
            model_name='individualpackage',
            name='important_package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.importantpackage'),
        ),
    ]
