# Generated by Django 3.2.5 on 2021-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_auto_20210809_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetype',
            old_name='image',
            new_name='left_image_1',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='left_image_2',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='left_image_3',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='left_image_4',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='left_image_5',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='left_image_6',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_1',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_2',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_3',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_4',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_5',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetype',
            name='right_image_6',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
