# Generated by Django 3.2.5 on 2021-08-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_auto_20210809_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetype',
            old_name='left_image_1',
            new_name='image',
        ),
    ]
