# Generated by Django 3.2.5 on 2021-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_rename_left_image_1_packagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='left_image_1',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
