# Generated by Django 4.0.2 on 2022-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_packagetype_left_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comfort_name', models.CharField(max_length=1024)),
                ('comfort_duration', models.CharField(max_length=50)),
                ('comfort_rate', models.CharField(max_length=50)),
                ('compact_name', models.CharField(max_length=1024)),
                ('compact_duration', models.CharField(max_length=50)),
                ('compact_rate', models.CharField(max_length=50)),
                ('itinerary_day_1', models.CharField(max_length=2055)),
                ('itinerary_day_2', models.CharField(max_length=2055)),
                ('itinerary_day_3', models.CharField(max_length=2055)),
                ('itinerary_day_4', models.CharField(max_length=2055)),
                ('itinerary_day_5', models.CharField(max_length=2055)),
                ('itinerary_day_6', models.CharField(max_length=2055)),
                ('itinerary_day_7', models.CharField(max_length=2055)),
                ('itinerary_day_8', models.CharField(max_length=2055)),
                ('itinerary_day_9', models.CharField(max_length=2055)),
                ('itinerary_day_10', models.CharField(max_length=2055)),
                ('itinerary_day_11', models.CharField(max_length=2055)),
                ('itinerary_day_12', models.CharField(max_length=2055)),
                ('itinerary_day_13', models.CharField(max_length=2055)),
                ('regular_grp_comfort_rate_1', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_2', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_3', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_4', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_1', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_2', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_3', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_4', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_1', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_2', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_3', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_4', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_1', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_2', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_3', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_4', models.CharField(max_length=255)),
                ('scheduled_rate_1', models.CharField(max_length=255)),
                ('scheduled_rate_2', models.CharField(max_length=255)),
                ('GST', models.CharField(max_length=3)),
            ],
        ),
    ]
