# Generated by Django 4.0.2 on 2022-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_currenttours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttours',
            name='GST',
            field=models.CharField(default=5, max_length=3),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_10',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_11',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_12',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_13',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_5',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_6',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_7',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_8',
            field=models.CharField(default=False, max_length=2055),
        ),
        migrations.AlterField(
            model_name='currenttours',
            name='itinerary_day_9',
            field=models.CharField(default=False, max_length=2055),
        ),
    ]
