# Generated by Django 4.0.2 on 2022-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_alter_currenttours_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttours',
            name='tour_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
