# Generated by Django 4.0.2 on 2022-02-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_currenttours_accommodation_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentImpTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_tour_name', models.CharField(max_length=255)),
                ('destinations', models.CharField(max_length=1024)),
                ('starting_at', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_number', models.IntegerField()),
                ('comfort_name', models.CharField(max_length=1024)),
                ('comfort_duration', models.CharField(max_length=50)),
                ('comfort_rate', models.CharField(max_length=50)),
                ('compact_name', models.CharField(max_length=1024)),
                ('compact_duration', models.CharField(max_length=50)),
                ('compact_rate', models.CharField(max_length=50)),
                ('itinerary_day_1', models.CharField(max_length=2055)),
                ('itinerary_day_2', models.CharField(max_length=2055)),
                ('itinerary_day_3', models.CharField(max_length=2055)),
                ('itinerary_day_4', models.CharField(max_length=2055)),
                ('itinerary_day_5', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_6', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_7', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_8', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_9', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_10', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_11', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_12', models.CharField(default=False, max_length=2055)),
                ('itinerary_day_13', models.CharField(default=False, max_length=2055)),
                ('regular_grp_comfort_rate_1', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_2', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_3', models.CharField(max_length=255)),
                ('regular_grp_comfort_rate_4', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_1', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_2', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_3', models.CharField(max_length=255)),
                ('regular_grp_compact_rate_4', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_1', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_2', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_3', models.CharField(max_length=255)),
                ('regular_couple_comfort_rate_4', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_1', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_2', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_3', models.CharField(max_length=255)),
                ('regular_couple_compact_rate_4', models.CharField(max_length=255)),
                ('scheduled_rate_1', models.CharField(max_length=255)),
                ('scheduled_rate_2', models.CharField(max_length=255)),
                ('accommodation_1', models.CharField(max_length=1024)),
                ('accommodation_2', models.CharField(max_length=1024)),
                ('accommodation_3', models.CharField(default=False, max_length=1024)),
                ('accommodation_4', models.CharField(default=False, max_length=1024)),
                ('accommodation_5', models.CharField(default=False, max_length=1024)),
                ('accommodation_6', models.CharField(default=False, max_length=1024)),
                ('GST', models.CharField(default=5, max_length=3)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.currentimptour')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentTours',
        ),
    ]
