# Generated by Django 4.0.2 on 2022-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_currentimptour_currenttour_delete_currenttours'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttour',
            name='note_1',
            field=models.CharField(default=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttour',
            name='note_2',
            field=models.CharField(default=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttour',
            name='note_3',
            field=models.CharField(default=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttour',
            name='note_4',
            field=models.CharField(default=False, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttour',
            name='note_5',
            field=models.CharField(default=False, max_length=2048),
        ),
        migrations.AddField(
            model_name='currenttour',
            name='short_note',
            field=models.CharField(default=False, max_length=2048),
            preserve_default=False,
        ),
    ]
